using System;
using Lander.Helpers;
using Lander.src.Notifications.Dtos.Dto;
using Lander.src.Notifications.Dtos.InputDto;
using Lander.src.Notifications.Interfaces;
using Lander.src.Notifications.Models;
using Lander.src.Notifications.NotificationsHub;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
namespace Lander.src.Notifications.Implementation;
public class NotificationService : INotificationService
{
    private readonly NotificationContext _context;
    private readonly IHubContext<NotificationHub> _hubContext;
    private readonly IHttpContextAccessor _httpContextAccessor;
    public NotificationService(NotificationContext context, IHubContext<NotificationHub> hubContext, IHttpContextAccessor httpContextAccessor)
    {
        _context = context;
        _hubContext = hubContext;
        _httpContextAccessor = httpContextAccessor;
    }
    public async Task<IEnumerable<NotificationDto>> GetUserNotificationsAsync(int userId)
    {
        return await _context.Notifications
            .Where(n => n.RecipientUserId == userId)
            .OrderByDescending(n => n.CreatedDate)
            .Select(n => new NotificationDto
            {
                Id = n.Id,
                Title = n.Title,
                Message = n.Message,
                ActionType = n.ActionType,
                ActionTarget = n.ActionTarget,
                IsRead = n.IsRead,
                CreatedDate = n.CreatedDate,
                CreatedByGuid = n.CreatedByGuid,
                SenderUserId = n.SenderUserId,
                RecipientUserId = n.RecipientUserId
            }).ToListAsync();
    }
    public async Task MarkAsReadAsync(int notificationId)
    {
        var notification = await _context.Notifications
       .FirstOrDefaultAsync(n => n.Id == notificationId);
        if (notification != null)
        {
            var readNotification = new ReadNotification
            {
                // Id is omitted — auto-generated by the IDENTITY column
                Title = notification.Title,
                Message = notification.Message,
                ActionType = notification.ActionType,
                ActionTarget = notification.ActionTarget,
                IsRead = true,
                CreatedDate = notification.CreatedDate,
                CreatedByGuid = notification.CreatedByGuid,
                SenderUserId = notification.SenderUserId,
                RecipientUserId = notification.RecipientUserId
            };
            await _context.RunInTransactionAsync(async () =>
            {
                await _context.ReadNotifications.AddAsync(readNotification);
                _context.Notifications.Remove(notification);
                await _context.SaveEntitiesAsync();
                            });
        }
    }
    public async Task<NotificationDto> SendNotificationAsync(CreateNotificationInputDto createNotificationInputDto)
    {
        var currentUserGuid = _httpContextAccessor.HttpContext?.User?.Claims
         .FirstOrDefault(c => c.Type == "sub")?.Value;
        var notification = new Notification
        {
            Title = createNotificationInputDto.Title,
            Message = createNotificationInputDto.Message,
            ActionType = createNotificationInputDto.ActionType,
            ActionTarget = createNotificationInputDto.ActionTarget,
            CreatedByGuid = Guid.TryParse(currentUserGuid, out var callerGuid) ? callerGuid : Guid.Empty,
            SenderUserId = createNotificationInputDto.SenderUserId,
            RecipientUserId = createNotificationInputDto.RecipientUserId,
            CreatedDate = DateTime.UtcNow,
        };
        await _context.RunInTransactionAsync(async () =>
        {
            _context.Notifications.Add(notification);
            await _context.SaveEntitiesAsync();
                    });
        var notificationDto = new NotificationDto
        {
            Id = notification.Id,
            Title = notification.Title,
            Message = notification.Message,
            ActionType = notification.ActionType,
            ActionTarget = notification.ActionTarget,
            IsRead = notification.IsRead
        };
        await _hubContext.Clients.All.SendAsync("ReceiveNotification", notificationDto);
        return notificationDto;
    }
    public async Task<bool> DeleteNotificationAsync(int notificationId)
    {
        var notification = await _context.Notifications
            .FirstOrDefaultAsync(n => n.Id == notificationId);
        if (notification == null) return false;
        await _context.RunInTransactionAsync(async () =>
        {
            _context.Notifications.Remove(notification);
            await _context.SaveEntitiesAsync();
                    });
        return true;
    }
    public async Task<bool> MarkAllAsReadAsync(int userId)
    {
        var notifications = await _context.Notifications
            .Where(n => n.RecipientUserId == userId && !n.IsRead)
            .ToListAsync();
        if (!notifications.Any()) return true;
        await _context.RunInTransactionAsync(async () =>
        {
            foreach (var notification in notifications)
            {
                var readNotification = new ReadNotification
                {
                    // Id is omitted — auto-generated by the IDENTITY column
                    Title = notification.Title,
                    Message = notification.Message,
                    ActionType = notification.ActionType,
                    ActionTarget = notification.ActionTarget,
                    IsRead = true,
                    CreatedDate = notification.CreatedDate,
                    CreatedByGuid = notification.CreatedByGuid,
                    SenderUserId = notification.SenderUserId,
                    RecipientUserId = notification.RecipientUserId
                };
                await _context.ReadNotifications.AddAsync(readNotification);
            }
            _context.Notifications.RemoveRange(notifications);
            await _context.SaveEntitiesAsync();
                    });
        return true;
    }
    public async Task<NotificationDto?> GetNotificationByIdAsync(int notificationId)
    {
        var n = await _context.Notifications
            .AsNoTracking()
            .FirstOrDefaultAsync(n => n.Id == notificationId);
        if (n == null) return null;
        return new NotificationDto
        {
            Id = n.Id,
            Title = n.Title,
            Message = n.Message,
            ActionType = n.ActionType,
            ActionTarget = n.ActionTarget,
            IsRead = n.IsRead,
            CreatedDate = n.CreatedDate,
            CreatedByGuid = n.CreatedByGuid,
            SenderUserId = n.SenderUserId,
            RecipientUserId = n.RecipientUserId
        };
    }
}
