// <auto-generated />
using System;
using Lander;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lander.Migrations.Roommates
{
    [DbContext(typeof(RoommatesContext))]
    [Migration("20260127190855_AddRoommatesIndexes")]
    partial class AddRoommatesIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Roommates")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lander.src.Modules.Roommates.Models.Roommate", b =>
                {
                    b.Property<int>("RoommateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoommateId"));

                    b.Property<DateOnly?>("AvailableFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("AvailableUntil")
                        .HasColumnType("date");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("BudgetIncludes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("BudgetMax")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("BudgetMin")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Cleanliness")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("CreatedByGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("GuestsAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("Hobbies")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Lifestyle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LookingForApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("LookingForApartmentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LookingForRoomType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaximumStayMonths")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumStayMonths")
                        .HasColumnType("int");

                    b.Property<Guid?>("ModifiedByGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("PetFriendly")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Profession")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("SmokingAllowed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoommateId")
                        .HasName("PK__Roommates__RoommateId");

                    b.HasIndex("UserId");

                    b.ToTable("Roommates", "Roommates");
                });
#pragma warning restore 612, 618
        }
    }
}
